[package]
name = "pmgr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
flate2 = "1.0.34"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
